### ISSUE TITLE
Watch ingresses failed unexpectedly error after kubernetes upgrade

### ISSUE THREAD

**Issue by kmpartner** [nabsul/kcert#95]
I recently upgraded kubernetes from 1.24 to 1.27 in digitalOcean kubernetes.
After that I started to get error massage email (watch ingress failed unexpectedly) periodically shown below.

Manually upgrade certificates from port-forwarded dashboard seems to work.
docker image is nabsul/kcert:v1.2.0.
Is this error message affect auto update of certificate in the future?

Watch ingresses failed unexpectedly

The request was aborted.

   at System.Net.Http.Http2Connection.ThrowRequestAborted(Exception innerException)
   at System.Net.Http.Http2Connection.Http2Stream.CheckResponseBodyState()
   at System.Net.Http.Http2Connection.Http2Stream.TryReadFromBuffer(Span`1 buffer, Boolean partOfSyncRead)
   at System.Net.Http.Http2Connection.Http2Stream.ReadDataAsync(Memory`1 buffer, HttpResponseMessage responseMessage, CancellationToken cancellationToken)
   at k8s.LineSeparatedHttpContent.CancelableStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
   at System.IO.StreamReader.ReadLineAsyncInternal()
   at k8s.Watcher`1.<>c.<CreateWatchEventEnumerator>b__21_1[TR](Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+MoveNext()
   at k8s.Watcher`1.CreateWatchEventEnumerator(Func`1 streamReaderCreator, Action`1 onError, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at KCert.Services.K8sWatchClient.WatchInLoopAsync[T,L](String label, Func`1 watch, Func`3 callback) in /build/Services/K8sWatchClient.cs:line 57
   at KCert.Services.K8sWatchClient.WatchInLoopAsync[T,L](String label, Func`1 watch, Func`3 callback) in /build/Services/K8sWatchClient.cs:line 57
   at KCert.Services.K8sWatchClient.WatchIngressesAsync(Func`3 callback, CancellationToken tok) in /build/Services/K8sWatchClient.cs:line 39
   at KCert.Services.IngressMonitorService.WatchIngressesAsync(CancellationToken tok) in /build/Services/IngressMonitorService.cs:line 54
   at KCert.Services.ExponentialBackoff.DoWithExponentialBackoffAsync(String actionName, Func`1 action, CancellationToken tok) in /build/Services/ExponentialBackoff.cs:line 29

**Comment by nabsul** [comment]
Sorry for the delayed response. It's possible that the newer kubernetes version is not compatible with the current version of KCert. I'll try to find some time to test this out.

If you have any additional information, please do share. Thanks!
